Resources:   
  DatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription:
      SubnetIds: 
      Tags:
        - Key:
          Value:

  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage:
      AvailabilityZone:
      BackupRetentionPeriod:
      DBInstanceClass:
      DBInstanceIdentifier:
      DBName: 
      DBSubnetGroupName:
      Engine:
      EngineVersion:
      MasterUsername:
      MasterUserPassword:
      MultiAZ:
      VPCSecurityGroups: